[project]
name = "my-first-langgraphjs"
version = "0.1.0"
description = "My first langgraph.js"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "jupyterlab>=4.4.5",
]
